import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

function readRepoFile(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

test("jobs filters support scoped search, removable chips, compact filters, and salary range", () => {
  const querySource = readRepoFile("src/lib/queries/jobs.ts");
  const filterContractSource = readRepoFile("src/lib/job-filter-contract.ts");
  const pageSource = readRepoFile("src/app/jobs/page.tsx");
  const filterFieldSource = readRepoFile("src/components/jobs/jobs-filter-field.tsx");
  const searchFormSource = readRepoFile("src/components/jobs/jobs-search-form.tsx");

  assert.match(querySource, /location\?: string/);
  assert.match(querySource, /searchScope\?: JobSearchScope/);
  assert.match(querySource, /titleSearch\?: string/);
  assert.match(querySource, /companySearch\?: string/);
  assert.match(querySource, /locationSearch\?: string/);
  assert.match(querySource, /source\?: string/);
  assert.match(querySource, /employmentType\?: string/);
  assert.match(querySource, /careerStage\?: string/);
  assert.match(querySource, /roleCategory\?: string/);
  assert.match(querySource, /includeUnknownSalary\?: boolean/);
  assert.match(querySource, /posted\?: string/);
  assert.match(querySource, /salaryMax\?: number/);
  assert.match(querySource, /location:\s*\{\s*contains: filters\.location/);
  assert.match(querySource, /appendScopedTextSearchWhere\(where, "title", filters\.titleSearch\)/);
  assert.match(querySource, /appendScopedTextSearchWhere\(where, "company", filters\.companySearch\)/);
  assert.match(querySource, /appendLocationSearchWhere\(where, filters\.locationSearch\)/);
  assert.match(querySource, /return clauses\.length === 1 \? clauses\[0\] : \{ OR: clauses \}/);
  assert.match(querySource, /sourceMappings:\s*\{\s*some:\s*\{[\s\S]*sourceName:\s*\{\s*contains: filters\.source/);
  assert.match(querySource, /normalizedEmploymentType:\s*employmentTypes\.length > 0/);
  assert.match(querySource, /normalizedEmploymentTypeConfidence:\s*\{\s*gte: EMPLOYMENT_TYPE_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /normalizedCareerStage:\s*knownStages\.length > 0/);
  assert.match(querySource, /normalizedCareerStageConfidence:\s*\{\s*gte: CAREER_STAGE_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /normalizedIndustry:\s*industries\.length > 0/);
  assert.match(querySource, /normalizedIndustryConfidence:\s*\{\s*gte: INDUSTRY_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /normalizedRoleCategory/);
  assert.match(querySource, /normalizedRoleCategoryConfidence:\s*\{\s*gte: ROLE_CATEGORY_FILTER_CONFIDENCE_THRESHOLD/);
  assert.match(querySource, /classificationStatus:\s*\{\s*in:\s*\[\.\.\.FILTERABLE_CLASSIFICATION_STATUSES\]/);
  assert.match(querySource, /assertJobFilterContract/);
  assert.match(filterContractSource, /getJobFilterContractViolations/);
  assert.match(filterContractSource, /role_category_mismatch/);
  assert.match(querySource, /withoutUnknownFilterValues/);
  assert.match(querySource, /postedAt:\s*\{\s*gte:/);
  assert.match(querySource, /buildSalaryRangeWhere\([\s\S]*filters\.salaryMin,[\s\S]*filters\.salaryMax,[\s\S]*filters\.salaryCurrency[\s\S]*Boolean\(filters\.includeUnknownSalary\)/);
  assert.match(querySource, /expandNormalizedRoleCategoryFilterValue\(filters\.roleCategory\)/);
  assert.match(querySource, /SALARY_COMPARISON_CURRENCIES/);
  assert.doesNotMatch(querySource, /salaryCurrency:\s*\{\s*notIn/);
  assert.match(querySource, /loadSalaryComparisonCurrency/);
  assert.match(querySource, /shouldUseJobFeedIndex\(filters: JobFilterParams, viewerProfileId: string \| null\)/);
  assert.match(querySource, /JOB_FEED_INDEX_COUNT_TIMEOUT_MS/);
  assert.match(querySource, /appendFeedIndexTextSearchWhere\(where, "company", filters\.companySearch\)/);
  assert.match(querySource, /appendFeedIndexTextSearchWhere\(where, "title", filters\.titleSearch\)/);
  assert.match(querySource, /appendFeedIndexLocationSearchWhere\(where, filters\.locationSearch\)/);
  assert.match(querySource, /canonicalJobIds = canonicalJobIds\.filter\(\(id\) => !passedJobIds\.has\(id\)\)/);
  assert.match(querySource, /searchJobIds\(\s*filters\.search,\s*filters\.searchScope \?\? "all"/);
  assert.match(querySource, /buildSearchTermVariants/);
  assert.match(querySource, /const tsQuery = toTsQuery\(query\)/);
  assert.match(querySource, /\.join\("\\n        AND "\)/);
  assert.match(querySource, /repeated-character typo variants/);
  assert.match(querySource, /OR location ILIKE \$\{param\}/);
  assert.match(querySource, /type JobSortBy = "relevance" \| "newest" \| "deadline" \| "company"/);
  assert.match(querySource, /normalizeJobSortBy\(inputFilters\.sortBy\)/);
  assert.doesNotMatch(querySource, /filters\.sortBy === "salary"/);
  assert.doesNotMatch(querySource, /filters\.sortBy === "location"/);

  assert.match(pageSource, /buildActiveFilterGroups\(filters, resolvedSearchParams\)/);
  assert.match(pageSource, /visibleResultFloor/);
  assert.match(pageSource, /jobsResult\.hasNextPage[\s\S]*jobsResult\.total === null/);
  assert.match(pageSource, /buildLocationSearchRemoveHref/);
  assert.match(pageSource, /currentHadValues/);
  assert.match(pageSource, /return "\/jobs\?reset=1"/);
  assert.match(pageSource, /normalizeSearchParamsForHref\(params\)/);
  assert.match(pageSource, /if \(rawSearch && selectedSearchScope === "title"\)/);
  assert.match(pageSource, /else if \(search\) \{[\s\S]*titleSearch = undefined;[\s\S]*companySearch = undefined;[\s\S]*locationSearch = undefined;/);
  assert.match(pageSource, /splitFilterValues\(filters\.locationSearch\)/);
  assert.match(pageSource, /Clear all/);
  assert.equal(pageSource.match(/Clear all/g)?.length, 1);
  assert.match(pageSource, /name="salaryMax"/);
  assert.match(pageSource, /name="salaryCurrency"/);
  assert.match(pageSource, /name="includeUnknownSalary"/);
  assert.match(pageSource, /SALARY_COMPARISON_CURRENCIES\.map/);
  assert.match(pageSource, /\{ label: "Expiry date", value: "deadline" \}/);
  assert.match(pageSource, /\{ label: "Company name", value: "company" \}/);
  assert.doesNotMatch(pageSource, /\{ label: "Salary", value: "salary" \}/);
  assert.doesNotMatch(pageSource, /\{ label: "Location", value: "location" \}/);
  assert.match(pageSource, /getSearchParam\(searchParams, "sortBy"\) \?\? getSearchParam\(searchParams, "sort"\)/);
  assert.match(pageSource, /href=\{buildJobsHref\(resolvedSearchParams,[\s\S]*sortBy: option\.value/);
  assert.match(pageSource, /<FilterToggleField[\s\S]*name="expiry"[\s\S]*value="soon"/);
  assert.match(pageSource, /className="sm:col-span-2"[\s\S]*name="careerStage"/);
  assert.match(pageSource, /name="jobFunction"/);
  assert.match(pageSource, /title="Job function"/);
  assert.match(pageSource, /Job Function/);
  assert.match(pageSource, /name="industry"/);
  assert.match(pageSource, /Jobs must match all active filter sections/);
  assert.match(filterFieldSource, /"use client"/);
  assert.match(filterFieldSource, /setSelectedValues/);
  assert.match(filterFieldSource, /selectedLabels\.length/);
  assert.doesNotMatch(pageSource, /title="Deadline"/);
  assert.match(searchFormSource, /name="searchScope"/);
  assert.match(searchFormSource, /const SEARCH_SCOPE_OPTIONS/);
  assert.match(searchFormSource, /\{ label: "All", value: "all" \}/);
  assert.match(searchFormSource, /titleSearch/);
  assert.match(searchFormSource, /companySearch/);
  assert.match(searchFormSource, /locationSearch/);
  assert.match(pageSource, /name="employmentType"/);
  assert.match(pageSource, /name="posted"/);
  assert.doesNotMatch(pageSource, /name="source"/);
  assert.doesNotMatch(pageSource, /name="status"/);
  assert.doesNotMatch(pageSource, /const REGION_OPTIONS/);
});
