ALTER TABLE "JobCanonical"
  ADD COLUMN "titleConfidence" DOUBLE PRECISION,
  ADD COLUMN "titleStatus" TEXT,
  ADD COLUMN "titleSource" TEXT,
  ADD COLUMN "titleCandidatesJson" JSONB,
  ADD COLUMN "locationConfidence" DOUBLE PRECISION,
  ADD COLUMN "locationStatus" TEXT,
  ADD COLUMN "locationSource" TEXT,
  ADD COLUMN "locationCandidatesJson" JSONB,
  ADD COLUMN "salaryStatus" TEXT,
  ADD COLUMN "salaryPeriod" TEXT,
  ADD COLUMN "salaryRawText" TEXT,
  ADD COLUMN "salaryConfidence" DOUBLE PRECISION,
  ADD COLUMN "salarySource" TEXT,
  ADD COLUMN "descriptionStatus" TEXT,
  ADD COLUMN "descriptionConfidence" DOUBLE PRECISION,
  ADD COLUMN "descriptionWordCount" INTEGER,
  ADD COLUMN "extractionWarnings" JSONB,
  ADD COLUMN "extractionRejectionReasons" JSONB;

ALTER TABLE "NormalizedJobRecord"
  ADD COLUMN "titleConfidence" DOUBLE PRECISION,
  ADD COLUMN "titleStatus" TEXT,
  ADD COLUMN "titleSource" TEXT,
  ADD COLUMN "titleCandidatesJson" JSONB,
  ADD COLUMN "locationConfidence" DOUBLE PRECISION,
  ADD COLUMN "locationStatus" TEXT,
  ADD COLUMN "locationSource" TEXT,
  ADD COLUMN "locationCandidatesJson" JSONB,
  ADD COLUMN "salaryStatus" TEXT,
  ADD COLUMN "salaryPeriod" TEXT,
  ADD COLUMN "salaryRawText" TEXT,
  ADD COLUMN "salaryConfidence" DOUBLE PRECISION,
  ADD COLUMN "salarySource" TEXT,
  ADD COLUMN "descriptionStatus" TEXT,
  ADD COLUMN "descriptionConfidence" DOUBLE PRECISION,
  ADD COLUMN "descriptionWordCount" INTEGER,
  ADD COLUMN "extractionWarnings" JSONB,
  ADD COLUMN "extractionRejectionReasons" JSONB;

ALTER TABLE "JobFeedIndex"
  ADD COLUMN "titleConfidence" DOUBLE PRECISION,
  ADD COLUMN "titleStatus" TEXT,
  ADD COLUMN "titleSource" TEXT,
  ADD COLUMN "locationConfidence" DOUBLE PRECISION,
  ADD COLUMN "locationStatus" TEXT,
  ADD COLUMN "locationSource" TEXT,
  ADD COLUMN "salaryStatus" TEXT,
  ADD COLUMN "salaryPeriod" TEXT,
  ADD COLUMN "salaryRawText" TEXT,
  ADD COLUMN "salaryConfidence" DOUBLE PRECISION,
  ADD COLUMN "salarySource" TEXT,
  ADD COLUMN "descriptionStatus" TEXT,
  ADD COLUMN "descriptionConfidence" DOUBLE PRECISION,
  ADD COLUMN "descriptionWordCount" INTEGER,
  ADD COLUMN "extractionWarnings" JSONB;
