UPDATE "Company"
SET "normalizedIndustry" = CASE "normalizedIndustry"
  WHEN 'FINANCE_BANKING' THEN 'FINANCIAL_SERVICES'
  WHEN 'INSURANCE' THEN 'FINANCIAL_SERVICES'
  WHEN 'MANUFACTURING_INDUSTRIAL' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'AUTOMOTIVE' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'ENERGY_UTILITIES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'AGRICULTURE_NATURAL_RESOURCES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'LEGAL' THEN 'LEGAL_SERVICES'
  WHEN 'OTHER_UNKNOWN' THEN 'UNKNOWN'
  ELSE "normalizedIndustry"
END
WHERE "normalizedIndustry" IN (
  'FINANCE_BANKING',
  'INSURANCE',
  'MANUFACTURING_INDUSTRIAL',
  'AUTOMOTIVE',
  'ENERGY_UTILITIES',
  'AGRICULTURE_NATURAL_RESOURCES',
  'LEGAL',
  'OTHER_UNKNOWN'
);

UPDATE "JobCanonical"
SET "normalizedIndustry" = CASE "normalizedIndustry"
  WHEN 'FINANCE_BANKING' THEN 'FINANCIAL_SERVICES'
  WHEN 'INSURANCE' THEN 'FINANCIAL_SERVICES'
  WHEN 'MANUFACTURING_INDUSTRIAL' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'AUTOMOTIVE' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'ENERGY_UTILITIES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'AGRICULTURE_NATURAL_RESOURCES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'LEGAL' THEN 'LEGAL_SERVICES'
  WHEN 'OTHER_UNKNOWN' THEN 'UNKNOWN'
  ELSE "normalizedIndustry"
END
WHERE "normalizedIndustry" IN (
  'FINANCE_BANKING',
  'INSURANCE',
  'MANUFACTURING_INDUSTRIAL',
  'AUTOMOTIVE',
  'ENERGY_UTILITIES',
  'AGRICULTURE_NATURAL_RESOURCES',
  'LEGAL',
  'OTHER_UNKNOWN'
);

UPDATE "NormalizedJobRecord"
SET "normalizedIndustry" = CASE "normalizedIndustry"
  WHEN 'FINANCE_BANKING' THEN 'FINANCIAL_SERVICES'
  WHEN 'INSURANCE' THEN 'FINANCIAL_SERVICES'
  WHEN 'MANUFACTURING_INDUSTRIAL' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'AUTOMOTIVE' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'ENERGY_UTILITIES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'AGRICULTURE_NATURAL_RESOURCES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'LEGAL' THEN 'LEGAL_SERVICES'
  WHEN 'OTHER_UNKNOWN' THEN 'UNKNOWN'
  ELSE "normalizedIndustry"
END
WHERE "normalizedIndustry" IN (
  'FINANCE_BANKING',
  'INSURANCE',
  'MANUFACTURING_INDUSTRIAL',
  'AUTOMOTIVE',
  'ENERGY_UTILITIES',
  'AGRICULTURE_NATURAL_RESOURCES',
  'LEGAL',
  'OTHER_UNKNOWN'
);

UPDATE "JobFeedIndex"
SET "normalizedIndustry" = CASE "normalizedIndustry"
  WHEN 'FINANCE_BANKING' THEN 'FINANCIAL_SERVICES'
  WHEN 'INSURANCE' THEN 'FINANCIAL_SERVICES'
  WHEN 'MANUFACTURING_INDUSTRIAL' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'AUTOMOTIVE' THEN 'MANUFACTURING_AUTOMOTIVE'
  WHEN 'ENERGY_UTILITIES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'AGRICULTURE_NATURAL_RESOURCES' THEN 'ENERGY_UTILITIES_NATURAL_RESOURCES'
  WHEN 'LEGAL' THEN 'LEGAL_SERVICES'
  WHEN 'OTHER_UNKNOWN' THEN 'UNKNOWN'
  ELSE "normalizedIndustry"
END
WHERE "normalizedIndustry" IN (
  'FINANCE_BANKING',
  'INSURANCE',
  'MANUFACTURING_INDUSTRIAL',
  'AUTOMOTIVE',
  'ENERGY_UTILITIES',
  'AGRICULTURE_NATURAL_RESOURCES',
  'LEGAL',
  'OTHER_UNKNOWN'
);
